### ISSUE TITLE
2회 천하제일 본선 풀이슬라이드 올려주세요

### ISSUE THREAD

**Issue by jh05013** [wookje/wookje.github.io#7]
fan

**Comment by Baekjoon** [comment]
:fan:

**Comment by jh05013** [comment]
2회 천하제일 본선 풀이슬라이드 올려주세요

**Comment by jh05013** [comment]
3회 천하제일 본선 풀이슬라이드 올려주세요

**Comment by Baekjoon** [comment]
16일이나 지났어요

**Comment by jh05013** [comment]
4회 천하제일 본선 풀이슬라이드 올려주세요

**Comment by jh05013** [comment]
5회 천하제일 본선 풀이슬라이드 올려주세요

**Comment by jh05013** [comment]
6회 천하제일 본선 풀이슬라이드 올려주세요

**Comment by jh05013** [comment]
@wookje

**Comment by jh05013** [comment]
7회 천하제일 본선 풀이슬라이드 올려주세요

**Comment by wookje** [comment]
http://wookje.dance/2018/10/13/%EC%A0%9C2%ED%9A%8C-%EC%B2%9C%ED%95%98%EC%A0%9C%EC%9D%BC-%EC%BD%94%EB%94%A9%EB%8C%80%ED%9A%8C-%EB%B3%B8%EC%84%A0-%ED%92%80%EC%9D%B4/

올렸습니다.
